name: Issue is created
on:
  issues:
    types: [opened]
jobs:
  display:
    runs-on: ubuntu-latest
      steps:
        - name: Display issue information
          run: echo {toJSON(github.event.issues)}